name: Container 
# How we can run job for multiple version and in batch.

on:
  push:
    branches:
      - master

jobs:
  # Simple add docker in action of a job
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:13.5.0-alpine3.10
    steps:
      - name: Log Node Version
        run: |
          node -v
          cat /etc/os-release
  # Run docker in individual steps.
  docker-step:
    runs-on: ubuntu-latest
    container:
      image: node:10.18.0-jessie
    steps:
      - name: Log Node Version
        run: node -v
      - name: Step with docker
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: /usr/local/bin/node
          args: -v
  # Execute own executable file in step.
  execute-own-executable:
    runs-on: ubuntu-latest
    container:
      image: node:10.18.0-jessie
    steps:
      - uses: actions/checkout@v1
      - name: List
        run: |
          pwd
          cat script.sh
      - name: Run a script
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: ./script.sh
          args: "Some String"
      