# Github Events workflow to check how we can invoke any workflow on events e.g pull_request. For that we require another branch as well.
name: Github Events

on: [pull_request]

jobs:
  Pull-Request-Action:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Action
        # We can use below mention action to fetch and checkout to the comment that causes this workflow to run.
        uses: actions/checkout@v3.3.0
      - name: List Directory
        run: |
          pwd
          ls