name: This is workflow name


on:
  push:
    branches:
      - master

jobs:
  this-is-job-name:
    runs-on: ubuntu-latest
    env:
      DB_HOSTNAME: ${{ secrets.DB_HOST_WORKFLOW }}
      DB_USER: ${{ secrets.DB_USER_WORKFLOW }}
      DB_PWD: ${{ secrets.DB_PWD_WORKFLOW }}

    steps:
      
      - name: echo a string
        run: echo "Hello World"
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mysqli

      - name: Install MySQL client
        uses: mirromutth/mysql-action@v1
        with:
          mysql version: '8.0'
          mysql database: ${{ secrets.DB_NAME_WORKFLOW }}
          mysql password: ${{ secrets.DB_PWD_WORKFLOW }}
          mysql user: ${{ secrets.DB_USER_WORKFLOW }}

      - name: Install Composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php --install-dir=bin --filename=composer
          php -r "unlink('composer-setup.php');"

      - name: Install dependencies
        run: composer install

      - name: Replace placeholders in .env file
        run: |
          envsubst < .env.sample > .env

      - name: Run tests
        run: |
          pwd
          ls
          ./vendor/bin/phpunit --verbose tests/UserTest.php

      - name: Restore Database
        run: |
          mysql -u${{ secrets.DB_USER_WORKFLOW }} -h${{ secrets.DB_HOST_WORKFLOW }} -e 'SELECT version();'
          mysql -u${{ secrets.DB_USER_WORKFLOW }} -h${{ secrets.DB_HOST_WORKFLOW }} -e 'create schema ${{ secrets.DB_NAME_WORKFLOW }};'
          mysql -u${{ secrets.DB_USER_WORKFLOW }} -h${{ secrets.DB_HOST_WORKFLOW }} -e 'SHOW DATABASES;'

      - name: List Database and tables
        run: |
          mysql -u${{ secrets.DB_USER_WORKFLOW }} -h${{ secrets.DB_HOST_WORKFLOW }} -e 'SHOW DATABASES;'
          mysql -u${{ secrets.DB_USER_WORKFLOW }} -h${{ secrets.DB_HOST_WORKFLOW }} ${{ secrets.DB_NAME_WORKFLOW }} < db/database.sql
          mysql -u${{ secrets.DB_USER_WORKFLOW }} -h${{ secrets.DB_HOST_WORKFLOW }} -e 'SHOW TABLES FROM ${{ secrets.DB_NAME_WORKFLOW }};'
          
      
          
