name: This is workflow name


on: [push]

jobs:
  this-is-job-name:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multile script
        run: |
          echo 'Command 1'
          echo 'Command 2'
          
