name: This is workflow name


on:
  push:
    branches:
      - master

jobs:
  this-is-job-name:
    runs-on: ubuntu-latest
    steps:
      
      - name: echo a string
        run: echo "Hello World"
      
      - name: multile script
        run: |
          echo 'Command 1'
          echo 'Command 2'
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install MySQL client
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '8.0'

      - name: Restore Database
        run: |
          mysql -uroot -h127.0.0.1 -e 'SELECT version();'
          mysql -uroot -h127.0.0.1 -e 'create schema af_ukrc;'
          mysql -uroot -h127.0.0.1 -e 'SHOW DATABASES;'

      - name: List Database and tables
        run: |
          mysql -uroot -h127.0.0.1 -e 'SHOW DATABASES;'
          mysql -uroot -h127.0.0.1 af_ukrc < db/database.sql
          mysql -uroot -h127.0.0.1 -e 'SHOW TABLES FROM af_ukrc;'
          
