name: This is workflow name


on:
  push:
    branches:
      - master

jobs:
  this-is-job-name:
    runs-on: ubuntu-latest
    env:
      extensions: mcrypt, curl, gd, intl, oauth, mysql, imagick, zip
      php-versions: '8.0'
      key: php-v8.0
      DB_HOSTNAME: ${{ secrets.DB_HOST_WORKFLOW }}
      DB_USER: ${{ secrets.DB_USER_WORKFLOW }}
      DB_PWD:

    steps:
      
      - name: echo a string
        run: echo "Hello World"
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php-versions }}
          extensions: ${{ env.extensions }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install composer dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist

#      - name: Install MySQL client
#        uses: mirromutth/mysql-action@v1
#        with:
#          mysql version: '8.0'
#          mysql database: ${{ secrets.DB_NAME_WORKFLOW }}
#          mysql password: ${{ secrets.DB_PWD_WORKFLOW }}
#          mysql user: ${{ secrets.DB_USER_WORKFLOW }}
      - name: Install MySQL client
        continue-on-error: true
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '8.0'

      - name: Replace placeholders in .env file
        run: |
          envsubst < .env.sample > .env

      - name: Run tests
        run: |
          pwd
          ls
          cat ${{ github.workspace }}/.env
          ./vendor/bin/phpunit --verbose tests/UserTest.php

      - name: Restore Database
        continue-on-error: true
        run: |
          mysql -h ${{ secrets.DB_HOST_WORKFLOW }} -u ${{ secrets.DB_USER_WORKFLOW }} -e 'SELECT version();'
          mysql -u${{ secrets.DB_USER_WORKFLOW }} -h${{ secrets.DB_HOST_WORKFLOW }} -e 'create schema ${{ secrets.DB_NAME_WORKFLOW }};'
          mysql -u${{ secrets.DB_USER_WORKFLOW }} -h${{ secrets.DB_HOST_WORKFLOW }} -e 'SHOW DATABASES;'

      - name: List Database and tables
        continue-on-error: true
        run: |
          mysql -u${{ secrets.DB_USER_WORKFLOW }} -h${{ secrets.DB_HOST_WORKFLOW }} -e 'SHOW DATABASES;'
          mysql -u${{ secrets.DB_USER_WORKFLOW }} -h${{ secrets.DB_HOST_WORKFLOW }} ${{ secrets.DB_NAME_WORKFLOW }} < db/database.sql
          mysql -u${{ secrets.DB_USER_WORKFLOW }} -h${{ secrets.DB_HOST_WORKFLOW }} -e 'SHOW TABLES FROM ${{ secrets.DB_NAME_WORKFLOW }};'
          
      
          
